#!/bin/sh
# installs or updates containr from github releases.
#
#   curl -fsSL https://raw.githubusercontent.com/suryavirkapur/containr/main/install.sh | sudo sh
#   curl -fsSL .../install.sh | sudo sh -s -- --domain example.com --email you@example.com
#
# first run: downloads the static binary, writes /opt/containr/containr.toml
# with random secrets and starts containr as a service (systemd, openrc,
# runit, dinit or sysvinit). later runs replace the binary with the newest
# (or --version) release and restart the service; the config is never
# overwritten. run with --help for options. posix sh, so it works on alpine.

set -eu
# shellcheck disable=SC3040
(set -o pipefail) 2>/dev/null && set -o pipefail

repo="${CONTAINR_REPO:-suryavirkapur/containr}"
version="${CONTAINR_VERSION:-}"
domain="${CONTAINR_DOMAIN:-}"
email="${CONTAINR_EMAIL:-}"
init="${CONTAINR_INIT:-auto}"
binary_path="${CONTAINR_BINARY:-/usr/local/bin/containr}"
install_dir="${CONTAINR_DIR:-/opt/containr}"
service="${CONTAINR_SERVICE:-containr}"
api_port=2077
config_only=0

usage() {
    cat <<'EOF'
usage: install.sh [options]

installs containr, or updates it when it's already installed.

options:
  --version VERSION   release to install, e.g. v0.1.16 (default: newest)
  --domain DOMAIN     root domain for service urls (first install only)
  --email EMAIL       let's encrypt contact email (first install only)
  --init INIT         auto, systemd, openrc, runit, dinit or sysvinit
                      (default: auto)
  --repo OWNER/REPO   github repo to install from
                      (default: suryavirkapur/containr)
  --config-only       only write containr.toml in the current directory
  -h, --help          show this help

every option can also be set with an env var: CONTAINR_VERSION,
CONTAINR_DOMAIN, CONTAINR_EMAIL, CONTAINR_INIT, CONTAINR_REPO,
CONTAINR_BINARY (default /usr/local/bin/containr), CONTAINR_DIR (default
/opt/containr) and CONTAINR_SERVICE (default containr). mirrors can set
CONTAINR_API_URL (a releases api) and CONTAINR_DOWNLOAD_URL.
EOF
}

say() { printf '\033[1m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[33mwarning:\033[0m %s\n' "$*" >&2; }
fail() { printf 'error: %s\n' "$*" >&2; exit 1; }

require_cmd() {
    command -v "$1" >/dev/null 2>&1 || fail "$1 is required"
}

while [ $# -gt 0 ]; do
    case "$1" in
        --version) shift; version="${1:-}" ;;
        --version=*) version="${1#*=}" ;;
        --domain) shift; domain="${1:-}" ;;
        --domain=*) domain="${1#*=}" ;;
        --email) shift; email="${1:-}" ;;
        --email=*) email="${1#*=}" ;;
        --init) shift; init="${1:-}" ;;
        --init=*) init="${1#*=}" ;;
        --repo) shift; repo="${1:-}" ;;
        --repo=*) repo="${1#*=}" ;;
        --config-only) config_only=1 ;;
        -h|--help) usage; exit 0 ;;
        *) usage >&2; fail "unknown option: $1" ;;
    esac
    shift
done

# writes a config with random secrets to $1 unless it exists
write_config() {
    path="$1"
    data_dir="$2"
    staging="true"
    if [ -f "$path" ]; then
        say "keeping existing $path"
        return
    fi
    require_cmd openssl
    [ -n "$email" ] && staging="false"
    mkdir -p "$(dirname "$path")" "$data_dir"
    old_umask="$(umask)"
    umask 077
    cat >"$path" <<EOF
# containr configuration, generated by install.sh
# see containr.example.toml in the repo for every option

[server]
host = "0.0.0.0"
port = $api_port

[database]
path = "$data_dir/containr.sqlite3"

[logging]
dir = "$data_dir/logs"
retention_days = 14

[proxy]
http_port = 80
https_port = 443
# services get <name>.<base_domain>; point a wildcard dns record here
base_domain = "$domain"
public_ip = ""
load_balance = "round_robin"

[github]
client_id = ""
client_secret = ""
webhook_secret = "$(openssl rand -hex 32)"

[auth]
jwt_secret = "$(openssl rand -hex 32)"
jwt_expiry_hours = 24

[security]
encryption_key = "$(openssl rand -hex 32)"

[acme]
email = "$email"
certs_dir = "$data_dir/certs"
# untrusted staging certificates until an email is set
staging = $staging

[storage]
data_dir = "$data_dir/storage"
max_volume_size_gb = 10
backup_enabled = false

[updates]
repo = "$repo"
EOF
    umask "$old_umask"
    say "wrote $path"
}

if [ "$config_only" = "1" ]; then
    write_config "$PWD/containr.toml" "$PWD/data"
    exit 0
fi

# ---- checks ---------------------------------------------------------------

[ "$(uname -s)" = "Linux" ] || fail "containr runs on linux only"
[ "$(id -u)" = "0" ] || fail "run as root, e.g. curl ... | sudo sh"
case "$(uname -m)" in
    x86_64|amd64) asset="containr-linux-amd64" ;;
    aarch64|arm64) asset="containr-linux-arm64" ;;
    *) fail "unsupported architecture: $(uname -m)" ;;
esac
require_cmd curl
require_cmd sha256sum
command -v docker >/dev/null 2>&1 \
    || fail "docker is required. install it first: https://docs.docker.com/engine/install/"
docker info >/dev/null 2>&1 || fail "docker is installed but not running"
command -v git >/dev/null 2>&1 \
    || warn "git isn't installed; it's needed to deploy from git repositories"

# ---- resolve the release --------------------------------------------------

api="${CONTAINR_API_URL:-https://api.github.com/repos/$repo/releases}"
tag_from() {
    sed -n 's/.*"tag_name": *"\([^"]*\)".*/\1/p' | head -n 1
}

if [ -z "$version" ]; then
    # newest stable release, else the newest prerelease
    version="$(curl -fsSL "$api/latest" 2>/dev/null | tag_from)" || true
    if [ -z "$version" ]; then
        version="$(curl -fsSL "$api?per_page=1" | tag_from)" \
            || fail "couldn't reach github"
    fi
    [ -n "$version" ] || fail "$repo has no releases yet"
fi
case "$version" in v*) ;; *) version="v$version" ;; esac
target="${version#v}"

current=""
if [ -x "$binary_path" ]; then
    current="$("$binary_path" --version 2>/dev/null | awk '{print $NF}')" || true
fi
if [ "$current" = "$target" ]; then
    say "containr $target is already installed"
    exit 0
fi

# ---- download and verify --------------------------------------------------

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT INT TERM
download="${CONTAINR_DOWNLOAD_URL:-https://github.com/$repo/releases/download}/$version"

say "downloading containr $target ($asset)"
curl -fSL --progress-bar "$download/$asset" -o "$tmp/$asset" \
    || fail "release $version has no $asset"
curl -fsSL "$download/$asset.sha256" -o "$tmp/$asset.sha256" \
    || fail "release $version has no $asset.sha256"
(cd "$tmp" && sha256sum -c "$asset.sha256" >/dev/null 2>&1) \
    || fail "checksum mismatch for $asset"
chmod 755 "$tmp/$asset"
reported="$("$tmp/$asset" --version | awk '{print $NF}')"
[ "$reported" = "$target" ] \
    || fail "downloaded binary reports $reported, expected $target"

# ---- install --------------------------------------------------------------

mkdir -p "$(dirname "$binary_path")"
if [ -f "$binary_path" ]; then
    cp -p "$binary_path" "$binary_path.previous"
fi
# copy next to the target, then rename so a running binary is swapped atomically
cp "$tmp/$asset" "$binary_path.new"
mv -f "$binary_path.new" "$binary_path"

if [ -n "$current" ]; then
    # an existing install keeps its service and config. never fall back to
    # the first-install steps: they would point the service at a new config
    # with new secrets and an empty database.
    "$binary_path" service restart --init "$init" --service-name "$service" \
        || fail "installed containr $target at $binary_path, but couldn't restart the $service service. restart it yourself (pass --init if the init system was guessed wrong). if containr never ran as a service, set one up with: $binary_path service install"
    say "updated containr $current -> $target"
    if [ ! -f "$install_dir/containr.toml" ]; then
        say "restarted $service; its config isn't in $install_dir, so check it's running yourself"
        exit 0
    fi
else
    write_config "$install_dir/containr.toml" "$install_dir/data"
    "$binary_path" service install \
        --init "$init" \
        --service-name "$service" \
        --binary-path "$binary_path" \
        --working-directory "$install_dir" \
        --config-path "$install_dir/containr.toml" \
        >/dev/null
    say "installed the $service service"
fi

# ---- wait for it ----------------------------------------------------------

configured_port="$(sed -n 's/^port *= *\([0-9][0-9]*\).*/\1/p' \
    "$install_dir/containr.toml" 2>/dev/null | head -n 1)" || true
api_port="${configured_port:-$api_port}"

i=0
while [ "$i" -lt 60 ]; do
    if curl -fsS "http://127.0.0.1:$api_port/health" 2>/dev/null \
        | grep -q "\"version\":\"$target\""; then
        if [ -n "$current" ]; then
            say "containr $target is running (previous binary: $binary_path.previous)"
        else
            say "containr $target is running"
            echo "    open http://<server-ip>:$api_port and create the first account; it becomes the admin."
            [ -n "$domain" ] || echo "    set proxy.base_domain in $install_dir/containr.toml, then: $binary_path service restart"
        fi
        exit 0
    fi
    i=$((i + 1))
    sleep 1
done

fail "containr didn't report $target on port $api_port within 60s. check its logs (journalctl -u $service, /var/log/$service*)"
