//! service definitions for the init systems containr can run under:
//! systemd, openrc, runit, dinit and sysvinit

use std::fmt;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::str::FromStr;
use std::time::Duration;

use anyhow::{anyhow, Context, Result};

use crate::systemd::{render_service_unit, ServiceUnitConfig};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InitSystem {
    Systemd,
    OpenRc,
    Runit,
    Dinit,
    SysVinit,
}

impl InitSystem {
    pub const ALL: [InitSystem; 5] = [
        InitSystem::Systemd,
        InitSystem::OpenRc,
        InitSystem::Runit,
        InitSystem::Dinit,
        InitSystem::SysVinit,
    ];

    pub fn name(self) -> &'static str {
        match self {
            InitSystem::Systemd => "systemd",
            InitSystem::OpenRc => "openrc",
            InitSystem::Runit => "runit",
            InitSystem::Dinit => "dinit",
            InitSystem::SysVinit => "sysvinit",
        }
    }

    /// the init system running this machine, from pid 1 and runtime dirs
    pub fn detect() -> Result<Self> {
        let pid1 = std::fs::read_to_string("/proc/1/comm")
            .map(|comm| comm.trim().to_string())
            .unwrap_or_default();
        detect_from(&pid1, |path| Path::new(path).exists()).ok_or_else(|| {
            anyhow!(
                "couldn't detect the init system (pid 1 is {:?}). pass \
                 --init with one of: {}",
                pid1,
                names()
            )
        })
    }
}

impl fmt::Display for InitSystem {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name())
    }
}

impl FromStr for InitSystem {
    type Err = anyhow::Error;

    fn from_str(value: &str) -> Result<Self> {
        let value = value.trim().to_ascii_lowercase();
        InitSystem::ALL
            .into_iter()
            .find(|init| init.name() == value)
            .or(match value.as_str() {
                "sysv" | "initd" => Some(InitSystem::SysVinit),
                _ => None,
            })
            .ok_or_else(|| {
                anyhow!(
                    "unknown init system {:?}. use one of: {}",
                    value,
                    names()
                )
            })
    }
}

fn names() -> String {
    InitSystem::ALL
        .iter()
        .map(|init| init.name())
        .collect::<Vec<_>>()
        .join(", ")
}

fn detect_from(
    pid1: &str,
    exists: impl Fn(&str) -> bool,
) -> Option<InitSystem> {
    if pid1 == "systemd" || exists("/run/systemd/system") {
        return Some(InitSystem::Systemd);
    }
    if pid1 == "openrc-init" || exists("/run/openrc") {
        return Some(InitSystem::OpenRc);
    }
    match pid1 {
        "dinit" => return Some(InitSystem::Dinit),
        "runit" | "runit-init" => return Some(InitSystem::Runit),
        _ => {}
    }
    if exists("/run/runit") {
        return Some(InitSystem::Runit);
    }
    if pid1 == "init" && exists("/etc/init.d") {
        return Some(InitSystem::SysVinit);
    }
    None
}

/// a file making up a service definition
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceFile {
    pub path: PathBuf,
    pub content: String,
    pub executable: bool,
}

/// files for `init`. runit paths depend on the distro layout, so they are
/// resolved against the running system.
pub fn render(
    init: InitSystem,
    config: &ServiceUnitConfig,
) -> Result<Vec<ServiceFile>> {
    // the systemd renderer validates names and paths for every init system
    let systemd_unit = render_service_unit(config)?;
    let name = &config.service_name;
    let exec = format!(
        "{} server --config {} --log-level {}",
        config.binary_path.display(),
        config.config_path.display(),
        config.log_level
    );
    let dir = config.working_directory.display();
    let root = config.user == "root";

    let files = match init {
        InitSystem::Systemd => vec![ServiceFile {
            path: config.default_output_path(),
            content: systemd_unit,
            executable: false,
        }],
        InitSystem::OpenRc => vec![ServiceFile {
            path: PathBuf::from("/etc/init.d").join(name),
            content: format!(
                "#!/sbin/openrc-run\n\
                 # generated by containr service install\n\
                 \n\
                 description=\"containr paas\"\n\
                 supervisor=supervise-daemon\n\
                 command=\"{binary}\"\n\
                 command_args=\"server --config {config} --log-level {level}\"\n\
                 {user}\
                 directory=\"{dir}\"\n\
                 output_log=\"/var/log/{name}.log\"\n\
                 error_log=\"/var/log/{name}.log\"\n\
                 respawn_delay=5\n\
                 respawn_max=0\n\
                 \n\
                 depend() {{\n\
                 \tneed net\n\
                 \tuse docker\n\
                 \tafter docker firewall\n\
                 }}\n",
                binary = config.binary_path.display(),
                config = config.config_path.display(),
                level = config.log_level,
                user = if root {
                    String::new()
                } else {
                    format!("command_user=\"{}\"\n", config.user)
                },
            ),
            executable: true,
        }],
        InitSystem::Runit => {
            let sv_dir = runit_sv_dir().join(name);
            let chpst = if root {
                String::new()
            } else {
                format!("chpst -u {} ", config.user)
            };
            vec![
                ServiceFile {
                    path: sv_dir.join("run"),
                    content: format!(
                        "#!/bin/sh\n\
                         # generated by containr service install\n\
                         exec 2>&1\n\
                         cd {dir} || exit 1\n\
                         exec {chpst}{exec}\n"
                    ),
                    executable: true,
                },
                ServiceFile {
                    path: sv_dir.join("log").join("run"),
                    content: format!(
                        "#!/bin/sh\n\
                         mkdir -p /var/log/{name}\n\
                         exec svlogd -tt /var/log/{name}\n"
                    ),
                    executable: true,
                },
            ]
        }
        InitSystem::Dinit => vec![ServiceFile {
            path: PathBuf::from("/etc/dinit.d").join(name),
            content: format!(
                "# generated by containr service install\n\
                 type = process\n\
                 command = {exec}\n\
                 working-dir = {dir}\n\
                 {user}\
                 restart = true\n\
                 smooth-recovery = true\n\
                 restart-delay = 5\n\
                 stop-timeout = 20\n\
                 logfile = /var/log/{name}.log\n",
                user = if root {
                    String::new()
                } else {
                    format!("run-as = {}\n", config.user)
                },
            ),
            executable: false,
        }],
        InitSystem::SysVinit => {
            if !root {
                return Err(anyhow!(
                    "the sysvinit script runs containr as root; --user isn't \
                     supported there"
                ));
            }
            vec![ServiceFile {
                path: PathBuf::from("/etc/init.d").join(name),
                content: sysvinit_script(name, &exec, &dir.to_string()),
                executable: true,
            }]
        }
    };
    Ok(files)
}

/// lsb init script; sysvinit doesn't supervise, so containr isn't restarted
/// if it crashes
fn sysvinit_script(name: &str, exec: &str, dir: &str) -> String {
    format!(
        r#"#!/bin/sh
### BEGIN INIT INFO
# Provides:          {name}
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Should-Start:      docker
# Should-Stop:       docker
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: containr paas
### END INIT INFO
# generated by containr service install

PIDFILE=/var/run/{name}.pid
LOG=/var/log/{name}.log

running() {{
    [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null
}}

start() {{
    if running; then
        echo "{name} is already running"
        return 0
    fi
    cd {dir} || return 1
    nohup {exec} >>"$LOG" 2>&1 &
    echo $! >"$PIDFILE"
    echo "started {name}"
}}

stop() {{
    if ! running; then
        rm -f "$PIDFILE"
        return 0
    fi
    kill "$(cat "$PIDFILE")"
    i=0
    while running && [ "$i" -lt 20 ]; do
        sleep 1
        i=$((i + 1))
    done
    running && kill -9 "$(cat "$PIDFILE")"
    rm -f "$PIDFILE"
    echo "stopped {name}"
}}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) stop; start ;;
    status)
        if running; then echo "{name} is running"; else echo "{name} is stopped"; exit 3; fi
        ;;
    *) echo "usage: $0 {{start|stop|restart|status}}"; exit 2 ;;
esac
"#
    )
}

/// writes the service files, enables the service and, when `start` is set,
/// (re)starts it. returns the written paths.
pub fn install(
    init: InitSystem,
    config: &ServiceUnitConfig,
    start: bool,
) -> Result<Vec<PathBuf>> {
    let files = render(init, config)?;
    for file in &files {
        write_file(file)?;
    }
    let name = config.service_name.as_str();

    match init {
        InitSystem::Systemd => {
            run("systemctl", &["daemon-reload"])?;
            run("systemctl", &["enable", name])?;
        }
        InitSystem::OpenRc => run("rc-update", &["add", name, "default"])?,
        InitSystem::Runit => {
            let link = runit_service_dir()?.join(name);
            let target = runit_sv_dir().join(name);
            if std::fs::symlink_metadata(&link).is_err() {
                std::os::unix::fs::symlink(&target, &link).with_context(
                    || format!("failed to link {}", link.display()),
                )?;
            }
        }
        // dinit starts a service when it's enabled; that's the restart below
        InitSystem::Dinit => {}
        InitSystem::SysVinit => {
            if command_exists("update-rc.d") {
                run("update-rc.d", &[name, "defaults"])?;
            } else if command_exists("chkconfig") {
                run("chkconfig", &["--add", name])?;
            } else if command_exists("rc-update") {
                run("rc-update", &["add", name, "default"])?;
            }
        }
    }

    // dinit has no enable-without-start; `dinitctl enable` in restart()
    // both starts the service and enables it at boot
    if start {
        restart(init, name)?;
    }

    Ok(files.into_iter().map(|file| file.path).collect())
}

/// restarts (or starts) the service
pub fn restart(init: InitSystem, name: &str) -> Result<()> {
    match init {
        InitSystem::Systemd => run("systemctl", &["restart", name]),
        InitSystem::OpenRc => run("rc-service", &[name, "restart"]),
        InitSystem::Runit => {
            // runsvdir picks up a new service within a few seconds
            let supervise = runit_sv_dir().join(name).join("supervise/ok");
            for _ in 0..20 {
                if supervise.exists() {
                    break;
                }
                std::thread::sleep(Duration::from_millis(500));
            }
            run("sv", &["restart", name])
        }
        InitSystem::Dinit => {
            if run("dinitctl", &["restart", name]).is_ok() {
                return Ok(());
            }
            run("dinitctl", &["enable", name])
        }
        InitSystem::SysVinit => {
            let script = PathBuf::from("/etc/init.d").join(name);
            run(&script.to_string_lossy(), &["restart"])
        }
    }
}

fn write_file(file: &ServiceFile) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;

    if let Some(parent) = file.path.parent() {
        std::fs::create_dir_all(parent).with_context(|| {
            format!("failed to create {}", parent.display())
        })?;
    }
    std::fs::write(&file.path, &file.content)
        .with_context(|| format!("failed to write {}", file.path.display()))?;
    let mode = if file.executable { 0o755 } else { 0o644 };
    std::fs::set_permissions(&file.path, std::fs::Permissions::from_mode(mode))
        .with_context(|| format!("failed to chmod {}", file.path.display()))
}

/// where runit service definitions live: /etc/runit/sv (artix) or /etc/sv
fn runit_sv_dir() -> PathBuf {
    let artix = PathBuf::from("/etc/runit/sv");
    if artix.is_dir() {
        artix
    } else {
        PathBuf::from("/etc/sv")
    }
}

/// the directory runsvdir watches for enabled services
fn runit_service_dir() -> Result<PathBuf> {
    [
        "/var/service",
        "/etc/runit/runsvdir/default",
        "/etc/service",
    ]
    .into_iter()
    .map(PathBuf::from)
    .find(|dir| dir.is_dir())
    .ok_or_else(|| anyhow!("couldn't find runit's service directory"))
}

fn command_exists(name: &str) -> bool {
    std::env::var_os("PATH").is_some_and(|paths| {
        std::env::split_paths(&paths).any(|dir| dir.join(name).is_file())
    })
}

fn run(program: &str, args: &[&str]) -> Result<()> {
    let output =
        Command::new(program).args(args).output().with_context(|| {
            format!("failed to run {} {}", program, args.join(" "))
        })?;
    if output.status.success() {
        return Ok(());
    }
    let stderr = String::from_utf8_lossy(&output.stderr);
    Err(anyhow!(
        "{} {} failed: {}",
        program,
        args.join(" "),
        stderr.trim()
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture() -> ServiceUnitConfig {
        ServiceUnitConfig {
            service_name: "containr".to_string(),
            user: "root".to_string(),
            working_directory: PathBuf::from("/opt/containr"),
            binary_path: PathBuf::from("/usr/local/bin/containr"),
            config_path: PathBuf::from("/opt/containr/containr.toml"),
            log_level: "info".to_string(),
        }
    }

    #[test]
    fn detects_init_from_pid1_and_runtime_dirs() {
        let none = |_: &str| false;
        assert_eq!(detect_from("systemd", none), Some(InitSystem::Systemd));
        assert_eq!(detect_from("runit", none), Some(InitSystem::Runit));
        assert_eq!(detect_from("dinit", none), Some(InitSystem::Dinit));
        // openrc on top of sysvinit's init
        assert_eq!(
            detect_from("init", |path| path == "/run/openrc"),
            Some(InitSystem::OpenRc)
        );
        assert_eq!(
            detect_from("init", |path| path == "/etc/init.d"),
            Some(InitSystem::SysVinit)
        );
        assert_eq!(detect_from("tini", none), None);
    }

    #[test]
    fn parses_init_names() {
        for init in InitSystem::ALL {
            assert_eq!(init.name().parse::<InitSystem>().ok(), Some(init));
        }
        assert_eq!(
            "sysv".parse::<InitSystem>().ok(),
            Some(InitSystem::SysVinit)
        );
        assert!("upstart".parse::<InitSystem>().is_err());
    }

    #[test]
    fn every_init_runs_the_server_with_the_config() {
        for init in InitSystem::ALL {
            let files = render(init, &fixture()).expect("render");
            let all = files
                .iter()
                .map(|file| file.content.as_str())
                .collect::<String>();
            assert!(all.contains("/usr/local/bin/containr"), "{init}");
            assert!(
                all.contains("server --config /opt/containr/containr.toml"),
                "{init}"
            );
        }
    }

    #[test]
    fn openrc_script_is_supervised() {
        let files = render(InitSystem::OpenRc, &fixture()).expect("render");
        assert_eq!(files[0].path, PathBuf::from("/etc/init.d/containr"));
        assert!(files[0].content.starts_with("#!/sbin/openrc-run"));
        assert!(files[0].content.contains("supervisor=supervise-daemon"));
        assert!(files[0].executable);
    }

    #[test]
    fn non_root_users_are_passed_to_the_init_system() {
        let mut config = fixture();
        config.user = "containr".to_string();
        let content =
            |init| render(init, &config).expect("render")[0].content.clone();
        assert!(
            content(InitSystem::OpenRc).contains("command_user=\"containr\"")
        );
        assert!(content(InitSystem::Runit).contains("chpst -u containr"));
        assert!(content(InitSystem::Dinit).contains("run-as = containr"));
        assert!(render(InitSystem::SysVinit, &config).is_err());
    }

    #[test]
    fn rejects_relative_paths_for_every_init() {
        let mut config = fixture();
        config.binary_path = PathBuf::from("containr");
        for init in InitSystem::ALL {
            assert!(render(init, &config).is_err(), "{init}");
        }
    }
}
